log:
  level: info # LOG LEVEL: error, warn, info, http, verbose, debug, silly
  dir: ./data/log # Directory to store log files

telegram:
  # channels dan whitelabel yang sudah tidak digunakan (deprecated)
  # Pindah ke pengaturan khusus di dalam masing-masing bot
  admin_ids:
    - 124324324 # Ganti dengan ID Telegram Anda
  bot:
    token: BOT_TOKEN
    api:
      protocol: http
      host: nginx
      port: 80
  botnotif:
    token: BOTNOTIF_TOKEN
    api:
      protocol: http
      host: nginx
      port: 80
